// exports.js — shared client-side exporters for planner results.
// KMZ via JSZip, GPX waypoints, CSV, GeoJSON, DXF. All with G-Geopylanner attribution.
// Strict ES module. Depends on global JSZip (loaded via CDN in HTML).

export const ATTRIBUTION = 'Generated by G-Geopylanner — free survey planning tool by Georesolve Africa — https://georesolveafrica.com/g-geopylanner';

function xmlEscape(value) {
  return String(value ?? '').replace(/[<>&"']/g, (c) => ({
    '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&apos;'
  }[c]));
}

function csvEscape(value) {
  const s = String(value ?? '');
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function downloadBlob(filename, blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
  try { window.showGGeopylannerLeadAfterExport?.(); } catch (err) { /* non-critical */ }
}

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
}

// Build the doc.kml string for a planner result.
// result = { lines:[{name,latlngs}], tieLines:[{name,latlngs}], points:[{label,latlng,lat,lon,color}], boundary:{latlngs} }
export function buildKML(result, meta = {}) {
  const folders = [];

  // Boundary folder
  if (result.boundary && result.boundary.latlngs && result.boundary.latlngs.length >= 3) {
    const ring = result.boundary.latlngs.map(([lat, lon]) => `${lon},${lat},0`).join(' ');
    folders.push(`
    <Folder>
      <name>Boundary</name>
      <Placemark>
        <name>Survey boundary</name>
        <styleUrl>#boundaryStyle</styleUrl>
        <Polygon><outerBoundaryIs><LinearRing><coordinates>${ring}</coordinates></LinearRing></outerBoundaryIs></Polygon>
      </Placemark>
    </Folder>`);
  }

  // Survey lines folder
  if (result.lines && result.lines.length) {
    const placemarks = result.lines.map((ln) => {
      const coords = (ln.latlngs || []).map(([lat, lon]) => `${lon},${lat},0`).join(' ');
      return `
      <Placemark>
        <name>${xmlEscape(ln.name || 'Line')}</name>
        <styleUrl>#lineStyle</styleUrl>
        <LineString><coordinates>${coords}</coordinates></LineString>
      </Placemark>`;
    }).join('');
    folders.push(`
    <Folder>
      <name>Survey lines</name>${placemarks}
    </Folder>`);
  }

  // Tie lines folder
  if (result.tieLines && result.tieLines.length) {
    const placemarks = result.tieLines.map((ln) => {
      const coords = (ln.latlngs || []).map(([lat, lon]) => `${lon},${lat},0`).join(' ');
      return `
      <Placemark>
        <name>${xmlEscape(ln.name || 'Tie')}</name>
        <styleUrl>#tieLineStyle</styleUrl>
        <LineString><coordinates>${coords}</coordinates></LineString>
      </Placemark>`;
    }).join('');
    folders.push(`
    <Folder>
      <name>Tie lines</name>${placemarks}
    </Folder>`);
  }

  // Points (stations / electrodes / geophones / shots) folder
  if (result.points && result.points.length) {
    const placemarks = result.points.map((p) => {
      const lat = p.latlng ? p.latlng[0] : p.lat;
      const lon = p.latlng ? p.latlng[1] : p.lon;
      if (!Number.isFinite(lat) || !Number.isFinite(lon)) return '';
      return `
      <Placemark>
        <name>${xmlEscape(p.label || p.id || 'Point')}</name>
        <description>${xmlEscape(p.description || '')}</description>
        <styleUrl>#pointStyle</styleUrl>
        <Point><coordinates>${lon},${lat},0</coordinates></Point>
      </Placemark>`;
    }).join('');
    folders.push(`
    <Folder>
      <name>${result.pointsFolderName || 'Stations'}</name>${placemarks}
    </Folder>`);
  }

  const docName = xmlEscape(meta.name || 'G-Geopylanner survey plan');
  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${docName}</name>
    <description>${xmlEscape(ATTRIBUTION)}</description>
    <Style id="boundaryStyle">
      <LineStyle><color>ff345363</color><width>2</width></LineStyle>
      <PolyStyle><color>264da34d</color><fill>1</fill><outline>1</outline></PolyStyle>
    </Style>
    <Style id="lineStyle">
      <LineStyle><color>ff27ae60</color><width>2</width></LineStyle>
    </Style>
    <Style id="tieLineStyle">
      <LineStyle><color>ffe67e22</color><width>2</width><dashStyle>dash</dashStyle></LineStyle>
    </Style>
    <Style id="pointStyle">
      <IconStyle><color>ff345363</color><scale>0.6</scale><Icon><href>https://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href></Icon></IconStyle>
      <LabelStyle><scale>0.7</scale></LabelStyle>
    </Style>${folders.join('')}
  </Document>
</kml>`;
}

export function exportKMZ(result, meta = {}) {
  if (!window.JSZip) throw new Error('JSZip library not loaded.');
  const zip = new JSZip();
  const kml = buildKML(result, meta);
  zip.file('doc.kml', kml);
  zip.file('README.txt', `${meta.name || 'G-Geopylanner survey plan'}\n\n${ATTRIBUTION}\nGenerated: ${new Date().toISOString()}\n`);
  return zip.generateAsync({ type: 'blob', compression: 'DEFLATE' }).then((blob) => {
    downloadBlob(`${meta.filename || 'geopylanner_plan'}_${timestamp()}.kmz`, blob);
  });
}

export function exportKML(result, meta = {}) {
  const kml = buildKML(result, meta);
  downloadBlob(`${meta.filename || 'geopylanner_plan'}_${timestamp()}.kml`, new Blob([kml], { type: 'application/vnd.google-earth.kml+xml' }));
}

export function exportGPX(result, meta = {}) {
  const wpts = (result.points || []).map((p) => {
    const lat = p.latlng ? p.latlng[0] : p.lat;
    const lon = p.latlng ? p.latlng[1] : p.lon;
    if (!Number.isFinite(lat) || !Number.isFinite(lon)) return '';
    return `
  <wpt lat="${lat}" lon="${lon}">
    <name>${xmlEscape(p.label || p.id || 'WP')}</name>
    <desc>${xmlEscape(p.description || '')}</desc>
  </wpt>`;
  }).join('');
  const routes = (result.lines || []).concat(result.tieLines || []).map((ln, i) => {
    const pts = (ln.latlngs || []).map(([lat, lon]) => `      <rtept lat="${lat}" lon="${lon}"><name>${xmlEscape(ln.name || `R${i + 1}`)}</name></rtept>`).join('\n');
    return `  <rte><name>${xmlEscape(ln.name || `Route ${i + 1}`)}</name>\n${pts}\n  </rte>`;
  }).join('\n');
  const gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="G-Geopylanner" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata><name>${xmlEscape(meta.name || 'G-Geopylanner plan')}</name><desc>${xmlEscape(ATTRIBUTION)}</desc></metadata>
${wpts}
${routes}
</gpx>`;
  downloadBlob(`${meta.filename || 'geopylanner_plan'}_${timestamp()}.gpx`, new Blob([gpx], { type: 'application/gpx+xml' }));
}

// CSV with per-point rows. Columns: line_id, point_id, chainage_m, easting, northing, utm_zone, latitude, longitude
export function exportCSV(result, meta = {}) {
  const header = `# ${ATTRIBUTION}\n# Generated: ${new Date().toISOString()}\n`;
  const cols = ['line_id', 'point_id', 'chainage_m', 'easting', 'northing', 'utm_zone', 'latitude', 'longitude'];
  if (meta.extraColumns) cols.push(...meta.extraColumns);
  const lines = [header + cols.join(',')];
  for (const p of (result.points || [])) {
    const row = [
      p.line_id ?? '',
      p.point_id ?? p.label ?? '',
      p.chainage ?? '',
      p.easting ?? '',
      p.northing ?? '',
      p.utm_zone || meta.utmZone || '',
      p.latlng ? p.latlng[0] : (p.lat ?? ''),
      p.latlng ? p.latlng[1] : (p.lon ?? '')
    ];
    if (meta.extraColumns) for (const c of meta.extraColumns) row.push(p[c] ?? '');
    lines.push(row.map(csvEscape).join(','));
  }
  const csv = lines.join('\n') + '\n';
  downloadBlob(`${meta.filename || 'geopylanner_plan'}_${timestamp()}.csv`, new Blob([csv], { type: 'text/csv' }));
}

export function exportGeoJSON(result, meta = {}) {
  const features = [];
  if (result.boundary && result.boundary.latlngs) {
    const ring = result.boundary.latlngs.map(([lat, lon]) => [lon, lat]);
    if (ring.length >= 3 && ring[0][0] !== ring[ring.length - 1][0]) ring.push(ring[0]);
    features.push({ type: 'Feature', properties: { name: 'boundary' }, geometry: { type: 'Polygon', coordinates: [ring] } });
  }
  for (const ln of (result.lines || [])) {
    features.push({ type: 'Feature', properties: { name: ln.name, kind: 'line' }, geometry: { type: 'LineString', coordinates: (ln.latlngs || []).map(([lat, lon]) => [lon, lat]) } });
  }
  for (const ln of (result.tieLines || [])) {
    features.push({ type: 'Feature', properties: { name: ln.name, kind: 'tie' }, geometry: { type: 'LineString', coordinates: (ln.latlngs || []).map(([lat, lon]) => [lon, lat]) } });
  }
  for (const p of (result.points || [])) {
    const lat = p.latlng ? p.latlng[0] : p.lat;
    const lon = p.latlng ? p.latlng[1] : p.lon;
    if (Number.isFinite(lat) && Number.isFinite(lon)) {
      features.push({ type: 'Feature', properties: { name: p.label, line_id: p.line_id, chainage: p.chainage, easting: p.easting, northing: p.northing }, geometry: { type: 'Point', coordinates: [lon, lat] } });
    }
  }
  const gj = { type: 'FeatureCollection', features, metadata: { generator: 'G-Geopylanner', attribution: ATTRIBUTION, generated: new Date().toISOString() } };
  downloadBlob(`${meta.filename || 'geopylanner_plan'}_${timestamp()}.geojson`, new Blob([JSON.stringify(gj, null, 2)], { type: 'application/geo+json' }));
}

// Minimal DXF: POLYLINE for lines, POINT for stations, LWPOLYLINE for boundary.
export function exportDXF(result, meta = {}) {
  const L = ['0', 'SECTION', '2', 'ENTITIES'];
  const layerOf = (name) => name.toUpperCase().replace(/[^A-Z0-9_-]/g, '').slice(0, 24) || 'SURVEY';

  if (result.boundary && result.boundary.utm && result.boundary.utm.length >= 3) {
    L.push('0', 'LWPOLYLINE', '8', 'BOUNDARY', '90', String(result.boundary.utm.length), '70', '1');
    for (const [x, y] of result.boundary.utm) L.push('10', String(x), '20', String(y), '30', '0');
  }

  for (const ln of (result.lines || [])) {
    if (!ln.utm || ln.utm.length < 2) continue;
    L.push('0', 'LWPOLYLINE', '8', layerOf(ln.name || 'LINES'), '90', String(ln.utm.length), '70', '0');
    for (const [x, y] of ln.utm) L.push('10', String(x), '20', String(y), '30', '0');
  }
  for (const ln of (result.tieLines || [])) {
    if (!ln.utm || ln.utm.length < 2) continue;
    L.push('0', 'LWPOLYLINE', '8', layerOf(ln.name || 'TIES'), '90', String(ln.utm.length), '70', '0');
    for (const [x, y] of ln.utm) L.push('10', String(x), '20', String(y), '30', '0');
  }
  for (const p of (result.points || [])) {
    if (!Number.isFinite(p.easting) || !Number.isFinite(p.northing)) continue;
    L.push('0', 'POINT', '8', layerOf(p.line_id || 'POINTS'), '10', String(p.easting), '20', String(p.northing), '30', '0');
    L.push('0', 'TEXT', '8', layerOf((p.line_id || 'POINTS') + '_LBL'), '10', String(p.easting), '20', String(p.northing), '30', '0', '40', '2.5', '1', String(p.label || ''));
  }
  L.push('0', 'ENDSEC', '0', 'EOF');
  const dxf = L.join('\n') + '\n';
  downloadBlob(`${meta.filename || 'geopylanner_plan'}_${timestamp()}.dxf`, new Blob([dxf], { type: 'application/dxf' }));
}

export function downloadText(filename, text, type = 'text/plain') {
  downloadBlob(filename, new Blob([text], { type }));
}
