import {headRay} from './spread.js?v=20261010-layout5';import {downloadText} from './exports.js?v=20261010-layout5';
const $=id=>document.getElementById(id),escape=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let current=null;
export function bindIllustration(){for(const id of ['gp-spread-select','gp-shot-select'])$(id).addEventListener('change',()=>draw());for(const id of ['gp-ray-v1','gp-ray-v2','gp-ray-h'])$(id).addEventListener('input',()=>draw());$('gp-diagram-export').onclick=()=>downloadText('g-physicsplanner-layout.svg',$('gp-diagram').innerHTML,'image/svg+xml');}
let generation=0;
export function renderIllustration(result){current=result;const show=result&&['seismic','ert'].includes(result.method);$('gp-illustrations').hidden=!show;if(!show)return;const ids=[...new Set(result.points.map(p=>p.spread||p.segment))];const previous=$('gp-spread-select').value;$('gp-spread-select').innerHTML=ids.map(id=>`<option>${escape(id)}</option>`).join('');if(ids.includes(previous))$('gp-spread-select').value=previous;draw();generation++;$('gp-illustration-status').textContent='Plan updated · '+generation+' · '+new Date().toLocaleTimeString();}
function draw(){if(!current)return;const id=$('gp-spread-select').value,points=current.points.filter(p=>(p.spread||p.segment)===id),receivers=points.filter(p=>p.kind!=='shot'),shots=points.filter(p=>p.kind==='shot');const select=$('gp-shot-select'),previous=select.value;select.innerHTML=shots.map(p=>`<option value="${escape(p.point_id)}">${escape(p.label)} · ${p.chainage} m (${p.shotType})</option>`).join('');if(shots.some(p=>p.point_id===previous))select.value=previous;select.parentElement.hidden=current.method==='ert';$('gp-ray-settings').hidden=current.method!=='seismic'||current.mode==='masw';if(!receivers.length){$('gp-diagram').textContent='No active receivers.';return;}
 const min=Math.min(...points.map(p=>p.chainage)),max=Math.max(...points.map(p=>p.chainage)),span=Math.max(max-min,1),x=c=>70+(c-min)/span*1050;const v1=Number($('gp-ray-v1').value),v2=Number($('gp-ray-v2').value),h=Number($('gp-ray-h').value);const surface=160,depthScale=170/Math.max(h,1);let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 450" role="img" aria-label="${escape(id)} survey layout and propagation illustration"><rect width="1200" height="450" fill="white"/><g font-family="Arial,sans-serif" font-size="13" fill="#24443f"><text x="50" y="30" font-size="20">${escape(id)} · ${current.method==='ert'?'ERT electrodes':current.mode==='masw'?'MASW spread':'SRT spread'}</text><text x="50" y="55">${receivers.length} ${current.method==='ert'?'electrodes':'geophones'} · active length ${(receivers.at(-1).chainage-receivers[0].chainage).toFixed(1)} m${shots.length?' · '+shots.length+' shots':''}</text><path d="M50 ${surface}H1150" stroke="#61776f"/>`;
 for(const p of receivers)svg+=`<circle cx="${x(p.chainage)}" cy="${surface}" r="4" fill="#2f825b"/><text x="${x(p.chainage)}" y="${surface+22}" text-anchor="middle" font-size="10">${p.electrode||p.point_id.split('_G')[1]}</text>`;
 for(const p of shots)svg+=`<path d="M${x(p.chainage)} ${surface-9}l-5 -9h10z" fill="${p.point_id===select.value?'#cd602b':'#aab4b0'}"/><text x="${x(p.chainage)}" y="${surface-28}" text-anchor="middle" font-size="10">SP${p.point_id.split('_SP')[1]}</text>`;
 for(let i=0;i<=5;i++)svg+=`<text x="${70+i*210}" y="100" text-anchor="middle">${(min+span*i/5).toFixed(1)} m</text>`;
 if(current.method==='ert'){
 $('gp-diagram-note').textContent='Electrode layout for '+current.stats.mode+'. The current-flow sketch below is conceptual for a local A–B source pair; it is not a quadrupole acquisition sequence, sensitivity model or depth prediction. ERT has electrodes and current injections, rather than seismic shots.';
 const a=receivers[0],b=receivers[Math.min(3,receivers.length-1)];for(let i=1;i<=4;i++)svg+=`<path d="M${x(a.chainage)} ${surface}C${x(a.chainage)} ${surface+35*i} ${x(b.chainage)} ${surface+35*i} ${x(b.chainage)} ${surface}" fill="none" stroke="#c78c3b" opacity=".7"/>`;svg+=`<text x="${x(a.chainage)}" y="140" text-anchor="middle">A</text><text x="${x(b.chainage)}" y="140" text-anchor="middle">B</text><text x="50" y="420">Conceptual current flow · not ray paths</text>`;
 }else if(current.mode==='masw'){
 $('gp-diagram-note').textContent='Selected-shot surface-wave propagation schematic. This illustrates source–receiver offsets; it is not a body-wave ray trace or a predicted dispersion/depth section.';const shot=shots.find(p=>p.point_id===select.value);if(shot){for(const r of receivers){const start=x(shot.chainage),end=x(r.chainage);svg+=`<path d="M${start} 210Q${(start+end)/2} 190 ${end} 210" stroke="#458b9b" fill="none" opacity=".35"/>`;}svg+=`<text x="50" y="320">Selected ${escape(shot.label)} · offset to first / last receiver: ${Math.abs(shot.chainage-receivers[0].chainage).toFixed(1)} / ${Math.abs(shot.chainage-receivers.at(-1).chainage).toFixed(1)} m</text>`;}else svg+='<text x="50" y="300">No shots configured.</text>';
 }else{
 $('gp-diagram-note').textContent='Selected-shot rays in a flat two-layer model. Grey: direct surface paths. Blue: critically refracted head-wave paths where geometrically possible. Dark blue arrives before the direct wave. Model is illustrative; actual rays require site velocities and interface geometry.';
 if(!(v1>0&&v2>v1&&h>0))svg+='<text x="50" y="300">Enter positive thickness and V2 greater than positive V1 for head waves.</text>';else{svg+=`<path d="M50 330H1150" stroke="#9caeac" stroke-dasharray="6 4"/><text x="50" y="375">Upper Vp ${v1} m/s · lower Vp ${v2} m/s · interface depth ${h} m · critical angle ${(Math.asin(v1/v2)*180/Math.PI).toFixed(1)}°</text>`;const shot=shots.find(p=>p.point_id===select.value);if(shot)for(const r of receivers){svg+=`<path d="M${x(shot.chainage)} ${surface}H${x(r.chainage)}" stroke="#939f9b" opacity=".3"/>`;const ray=headRay(shot.chainage,r.chainage,v1,v2,h);if(ray)svg+=`<path d="${ray.points.map(([c,d],i)=>(i?'L':'M')+x(c)+' '+(surface+d*depthScale)).join(' ')}" stroke="${ray.headTime<ray.directTime?'#126a91':'#a3c6d5'}" stroke-width="1.4" fill="none" opacity=".8"/>`;}else svg+='<text x="50" y="250">No shots configured.</text>';}}
 svg+='</g></svg>';$('gp-diagram').innerHTML=svg;$('gp-diagram').querySelector('svg').style.width='100%';}
