import {validateRow,parseCSV,csvCell,wrap,rose} from './math.js';
import {stereonet,rosePlot,combined,esc} from './plots.js';
import {FIELDS,FAVOR,ORIENTATION,CLASSES,calculateRMR,sampleRMR,blankRMR} from './rmr.js';
import {exportRMR} from './report.js';
const $=id=>document.getElementById(id),KEY='georesolve-g-structural-v1';
const sampleRows=()=>[...[[118,52],[125,58],[130,55],[122,61],[135,49],[128,54]].map((v,i)=>({id:'J1-'+(i+1),type:'plane',convention:'dd',azimuth:v[0],dip:v[1],group:'Joint set 1'})),...[[225,68],[230,72],[238,66],[232,75],[242,70],[235,69]].map((v,i)=>({id:'J2-'+(i+1),type:'plane',convention:'dd',azimuth:v[0],dip:v[1],group:'Joint set 2'})),...[[45,18],[52,22],[48,25]].map((v,i)=>({id:'L-'+(i+1),type:'line',convention:'dd',azimuth:v[0],dip:v[1],group:'Lineations'}))];
const defaults=()=>({version:1,title:'Example · joint sets and lineations',example:true,rows:sampleRows(),settings:{projection:'area',circles:true,poles:true,source:'strike',axial:true,bin:10,units:'count'},rmr:sampleRMR()});
let state=defaults(),storageOK=true;
try{const saved=localStorage.getItem(KEY);if(saved)state=checkWorkspace(JSON.parse(saved));}catch{storageOK=false;}
function checkWorkspace(data){if(data.version!==1||!Array.isArray(data.rows)||data.rows.length>5000||!data.rmr||typeof data.rmr!=='object')throw Error('Not a G-Structural v1 workspace (maximum 5,000 rows).');const d=defaults();const settings={...d.settings,...data.settings};if(!['area','angle'].includes(settings.projection)||!['strike','dd','trend'].includes(settings.source)||![5,10,15,20,30,45,60,90].includes(Number(settings.bin))||!['count','percent'].includes(settings.units)||typeof settings.axial!=='boolean'||typeof settings.circles!=='boolean'||typeof settings.poles!=='boolean')throw Error('Invalid plot settings in workspace.');return {...d,title:String(data.title??'Untitled').slice(0,100),example:!!data.example,rows:data.rows.map(r=>({id:String(r.id??'').slice(0,40),type:r.type,convention:r.convention,azimuth:r.azimuth,dip:r.dip,group:String(r.group??'').slice(0,60)})),settings,rmr:{...blankRMR(),...data.rmr}};}
function confirmReplace(message){return new Promise(resolve=>{const d=$('replace-dialog');$('replace-message').textContent=message;const finish=value=>{d.close();resolve(value);};$('replace-cancel').onclick=()=>finish(false);$('replace-confirm').onclick=()=>finish(true);d.oncancel=()=>resolve(false);d.showModal();});}
function status(message){$('gs-status').textContent=message;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;status('Browser saving is unavailable. Download a workspace backup to keep your work.');}}
function filename(suffix){return (state.title||'g-structural').replace(/[^a-z0-9]+/gi,'-').slice(0,60)+'-'+suffix;}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);status('Downloaded '+name);}
function renderPlots(){const valid=state.rows.filter(r=>!validateRow(r).length);$('stereonet-plot').innerHTML=stereonet(valid,state.settings);$('rose-plot').innerHTML=rosePlot(valid,state.settings);const rd=rose(valid,state.settings.source,state.settings.axial,Number(state.settings.bin));$('plot-summary').textContent=`${valid.length} valid measurements · ${rd.n} in rose · ${state.rows.length-valid.length} need attention`;const badge=$('data-badge');badge.textContent=state.example?'Synthetic example':'Your dataset';badge.classList.toggle('real',!state.example);for(const id of ['export-svg','export-png','export-csv'])$(id).disabled=!valid.length;}
const options=(arr,value)=>arr.map(([v,label])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(label)}</option>`).join('');
function rowHTML(r,i){const errors=validateRow(r);return `<tr data-row="${i}" class="${errors.length?'invalid':''}"><td><input aria-label="ID row ${i+1}" data-key="id" value="${esc(r.id)}" maxlength="40"></td><td><select aria-label="Type row ${i+1}" data-key="type">${options([['plane','Plane'],['line','Line']],r.type)}</select></td><td><select aria-label="Convention row ${i+1}" data-key="convention" ${r.type==='line'?'disabled':''}>${options(r.type==='line'?[['dd','Trend / plunge']]:[['dd','Dip direction / dip'],['rhr','RHR strike / dip']],r.convention)}</select></td><td><input aria-label="Azimuth row ${i+1}" data-key="azimuth" type="number" min="0" max="360" step="any" value="${esc(r.azimuth)}"></td><td><input aria-label="Dip or plunge row ${i+1}" data-key="dip" type="number" min="0" max="90" step="any" value="${esc(r.dip)}"></td><td><input aria-label="Group row ${i+1}" data-key="group" maxlength="60" value="${esc(r.group)}"></td><td class="row-check">${errors.length?esc(errors.join('; ')):'Valid'}</td><td><button data-remove="${i}" aria-label="Remove row ${i+1}">×</button></td></tr>`;}
function renderRows(){$('measurement-rows').innerHTML=state.rows.length?state.rows.map(rowHTML).join(''):'<tr><td colspan="8" class="empty">Add a plane or line, or import your measurements to begin.</td></tr>';}
function syncPlots(){$('dataset-title').value=state.title;$('projection').value=state.settings.projection;$('show-circles').checked=state.settings.circles;$('show-poles').checked=state.settings.poles;$('rose-source').value=state.settings.source;$('rose-mode').value=state.settings.axial?'axial':'directional';$('rose-bin').value=state.settings.bin;$('rose-units').value=state.settings.units;renderRows();renderPlots();}
$('measurement-rows').addEventListener('input',e=>{const k=e.target.dataset.key;if(!k)return;const tr=e.target.closest('tr'),i=Number(tr.dataset.row);state.rows[i][k]=e.target.value;if(k==='type'){state.rows[i].convention='dd';renderRows();}else{const errors=validateRow(state.rows[i]);tr.classList.toggle('invalid',!!errors.length);tr.querySelector('.row-check').textContent=errors.length?errors.join('; '):'Valid';}renderPlots();save();});
$('measurement-rows').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;state.rows.splice(Number(b.dataset.remove),1);renderRows();renderPlots();save();});
for(const type of ['plane','line'])$('add-'+type).onclick=()=>{if(state.rows.length>=5000){status('Maximum 5,000 measurements.');return;}state.rows.push({id:(type==='plane'?'P':'L')+'-'+(state.rows.length+1),type,convention:'dd',azimuth:'',dip:'',group:'Field measurements'});renderRows();renderPlots();save();};
$('dataset-title').oninput=e=>{state.title=e.target.value;save();};
$('clear-data').onclick=async()=>{if(!state.example&&state.rows.length&&!await confirmReplace('Clear the current measurements? Download a workspace first if you need to keep them.'))return;state.rows=[];state.title='My structural dataset';state.example=false;syncPlots();save();status('Clean dataset ready. Add measurements or import CSV.');};
$('load-sample').onclick=async()=>{if(!state.example&&state.rows.length&&!await confirmReplace('Replace current measurements with the synthetic example?'))return;state.rows=sampleRows();state.title='Example · joint sets and lineations';state.example=true;syncPlots();save();status('Synthetic joint sets loaded.');};
for(const [id,k] of [['projection','projection'],['show-circles','circles'],['show-poles','poles'],['rose-source','source'],['rose-mode','axial'],['rose-bin','bin'],['rose-units','units']])$(id).onchange=e=>{state.settings[k]=e.target.type==='checkbox'?e.target.checked:k==='axial'?e.target.value==='axial':k==='bin'?Number(e.target.value):e.target.value;renderPlots();save();};
$('export-svg').onclick=()=>download(combined(state.rows,state.settings,state.title,state.example),filename('figures.svg'),'image/svg+xml');
$('export-png').onclick=async()=>{try{const xml=combined(state.rows,state.settings,state.title,state.example),url=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=3150;canvas.height=Number(xml.match(/height="(\d+)"/)[1])*3;canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('PNG conversion failed.');download(blob,filename('figures.png'),'image/png');}finally{URL.revokeObjectURL(url);}}catch(e){status('PNG export failed: '+e.message);}};
$('export-csv').onclick=()=>{const keys=['id','type','azimuth','dip','convention','group'];download([keys.join(','),...state.rows.filter(r=>!validateRow(r).length).map(r=>keys.map(k=>csvCell(k==='azimuth'?wrap(Number(r[k])):r[k])).join(','))].join('\r\n'),filename('measurements.csv'),'text/csv');};
$('save-json').onclick=()=>download(JSON.stringify(state,null,2),filename('workspace.json'),'application/json');
$('open-json').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>4000000)throw Error('Workspace file exceeds 4 MB.');const next=checkWorkspace(JSON.parse(await file.text()));if(!await confirmReplace('Replace this workspace with '+file.name+'?'))return;state=next;syncPlots();syncRMR();save();status('Workspace opened: '+file.name);}catch(err){status('Could not open workspace: '+err.message);}finally{e.target.value='';}};
// CSV mapping is explicit; invalid observations remain visible for correction.
let csvRows=[],csvHeaders=[];
$('import-toggle').onclick=()=>{$('csv-panel').hidden=!$('csv-panel').hidden;};
$('csv-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>4000000){status('CSV file exceeds 4 MB.');return;}$('csv-text').value=await f.text();readColumns();e.target.value='';};
$('parse-csv').onclick=readColumns;
function readColumns(){try{const parsed=parseCSV($('csv-text').value);if(parsed.length<2)throw Error('Include a header row and at least one measurement.');csvHeaders=parsed.shift().map(x=>x.trim());csvRows=parsed;if(csvRows.length>5000)throw Error('Maximum 5,000 measurements.');const aliases={id:['id','station'],azimuth:['azimuth','dip_direction','dip direction','strike','trend'],dip:['dip','plunge'],type:['type'],convention:['convention'],group:['group','set']};$('csv-mapping').innerHTML='<div class="gs-mapping-grid">'+Object.entries(aliases).map(([key,names])=>{const found=csvHeaders.findIndex(h=>names.includes(h.toLowerCase()));return `<label>${key}<select id="map-${key}">${options([['','Use default / none'],...csvHeaders.map((h,i)=>[i,h])],found<0?'':found)}</select></label>`;}).join('')+`<label>Default interpretation (when type / convention columns are absent)<select id="csv-default">${options([['dd','Planes · dip direction / dip'],['rhr','Planes · RHR strike / dip'],['line','Lines · trend / plunge']],'dd')}</select></label><p class="gs-help">Mapped azimuth and dip / plunge columns are required. Replacing the example removes its fictional observations. Append adds rows to your existing data.</p><button id="csv-replace">Replace dataset</button><button id="csv-append">Append to dataset</button><pre id="csv-feedback" class="gs-rejections"></pre>`;$('csv-mapping').hidden=false;$('csv-replace').onclick=()=>applyCSV(false);$('csv-append').onclick=()=>applyCSV(true);status(`Read ${csvRows.length} rows. Confirm the orientation convention before importing.`);}catch(e){$('csv-mapping').hidden=true;status('CSV: '+e.message);}}
async function applyCSV(append){const maps=Object.fromEntries(['id','azimuth','dip','type','convention','group'].map(k=>[k,$('map-'+k).value]));if(maps.azimuth===''||maps.dip===''){status('Map azimuth and dip / plunge columns.');return;}if(append&&state.example){status('Start your dataset or use Replace to remove the example before appending field data.');return;}if(append&&state.rows.length+csvRows.length>5000){status('Maximum 5,000 measurements.');return;}if(!append&&!state.example&&state.rows.length&&!await confirmReplace('Replace all current measurements with imported rows?'))return;const def=$('csv-default').value,get=(row,k,fallback)=>maps[k]===''?fallback:(row[Number(maps[k])]??'').trim(),rows=csvRows.map((row,i)=>({id:get(row,'id','CSV-'+(i+1)),type:get(row,'type',def==='line'?'line':'plane').toLowerCase(),convention:get(row,'convention',def==='rhr'?'rhr':'dd').toLowerCase(),azimuth:get(row,'azimuth',''),dip:get(row,'dip',''),group:get(row,'group','Imported')}));const errors=rows.flatMap((r,i)=>{const e=validateRow(r);return e.length?[`CSV row ${i+2}: ${e.join('; ')}`]:[]});state.rows=append?[...state.rows,...rows]:rows;state.example=false;if(!append)state.title='Imported structural dataset';syncPlots();save();$('csv-feedback').textContent=errors.length?errors.slice(0,30).join('\n')+(errors.length>30?'\n…additional invalid rows are in the table.':''):'All imported rows are valid.';status(`Imported ${rows.length} rows; ${rows.length-errors.length} valid. Invalid rows are retained for correction and excluded from figures.`);}
// RMR assessment and exports.
for(const [k,f] of Object.entries(FIELDS)){const target=['persistence','aperture','roughness','infilling','weathering'].includes(k)?'condition-fields':'rmr-fields';$(target).insertAdjacentHTML('beforeend',`<label><span class="gs-field-head"><span>${esc(f.label)}</span><span id="rating-${k}" class="gs-rating">— / ${f.max}</span></span><select id="rmr-${k}"><option value="">Select observed category</option>${f.options.map(([label,score],i)=>`<option value="${i}">${esc(label)} · ${score}</option>`).join('')}</select></label>`);}
$('rmr-fields').insertAdjacentHTML('beforeend','<label><span class="gs-field-head"><span>Rock quality designation · RQD %</span><span id="rating-rqd" class="gs-rating">— / 20</span></span><input id="rmr-rqd" type="number" min="0" max="100" step="any" placeholder="0–100"></label>');
$('rmr-orientation').innerHTML='<option value="">Select assessed favourability</option>'+FAVOR.map((f,i)=>`<option value="${i}">${esc(f)}</option>`).join('');
$('class-table').innerHTML='<table aria-label="RMR89 rock classes"><tbody>'+CLASSES.map((c,i)=>`<tr><td>${c.id}</td><td>${c.min}–${i?CLASSES[i-1].min-1:100}</td><td>${c.name}</td></tr>`).join('')+'</tbody></table>';
function syncRMR(){for(const k of [...Object.keys(FIELDS),'rqd','station','notes','application','orientation'])$('rmr-'+k).value=state.rmr[k]??'';$('condition-mode').value=state.rmr.conditionMode||'detail';$('condition-overall').value=state.rmr.conditionOverall??'';renderRMR();}
function breakdown(result){return [['Intact strength',result.parts.strength],['RQD',result.parts.rqd],['Discontinuity spacing',result.parts.spacing],['Discontinuity condition',result.condition],['Groundwater',result.parts.water],['Basic RMR',result.basic],['Orientation adjustment',result.adjustment],['Raw adjusted total',result.raw],['Classification RMR (0–100)',result.total]];}
function renderRMR(){const r=calculateRMR(state.rmr);const overall=state.rmr.conditionMode==='overall';$('condition-fields').hidden=overall;$('overall-label').hidden=!overall;for(const [k,f] of Object.entries(FIELDS))$('rating-'+k).textContent=(r.parts[k]??'—')+' / '+f.max;$('rating-rqd').textContent=(r.parts.rqd??'—')+' / 20';const badge=$('rmr-badge');badge.textContent=state.rmr.example?'Synthetic example':'Your assessment';badge.classList.toggle('real',!state.rmr.example);$('rmr-pdf').disabled=$('rmr-copy').disabled=!r.complete;if(!r.complete){$('rmr-result').innerHTML='<div class="gs-score">—</div><p class="gs-class">Complete the assessment</p><p class="gs-help">Required: '+esc(r.errors.join(', '))+'.</p>';return;}$('rmr-result').innerHTML=`<div class="gs-score">${r.total}</div><p class="gs-class">Class ${r.rockClass.id} · ${r.rockClass.name}</p><div class="gs-scorebar" aria-hidden="true"><span></span><span></span><span></span><span></span><span></span></div><table class="gs-breakdown"><tbody>${breakdown(r).map(([k,v],i)=>`<tr class="${i>=5?'total':''}"><td>${esc(k)}</td><td>${v}</td></tr>`).join('')}</tbody></table>${r.raw<0?'<p class="gs-help">The raw total is negative; classification is floored at 0. The orientation penalty is retained above.</p>':''}`;}
for(const k of [...Object.keys(FIELDS),'rqd','station','notes','application','orientation'])$('rmr-'+k).addEventListener('input',e=>{state.rmr[k]=e.target.value;renderRMR();save();});
for(const [id,key] of [['condition-mode','conditionMode'],['condition-overall','conditionOverall']])$(id).onchange=e=>{state.rmr[key]=e.target.value;renderRMR();save();};
$('rmr-clear').onclick=async()=>{if(!state.rmr.example&&!await confirmReplace('Clear this assessment? Download a workspace to retain it first.'))return;state.rmr=blankRMR();syncRMR();save();status('Blank assessment ready. No rock class is assigned until all required observations are entered.');};
$('rmr-example').onclick=async()=>{if(!state.rmr.example&&!await confirmReplace('Replace this assessment with the synthetic example?'))return;state.rmr=sampleRMR();syncRMR();save();status('Synthetic RMR example loaded.');};
function assessmentLines(){const r=calculateRMR(state.rmr);if(!r.complete)throw Error('Complete the required RMR observations first.');const input=state.rmr,lines=['G-STRUCTURAL | GEORESOLVE AFRICA','RMR89 - Bieniawski (1989)',input.station||'Unnamed assessment',input.example?'SYNTHETIC EXAMPLE - not project observations':'Field assessment',`Application: ${input.application} | Orientation: ${FAVOR[Number(input.orientation)]}`,`Adjusted RMR: ${r.total} | Class ${r.rockClass.id} - ${r.rockClass.name}`,'','OBSERVATIONS AND RATINGS'];for(const [k,f] of Object.entries(FIELDS)){if(input.conditionMode==='overall'&&['persistence','aperture','roughness','infilling','weathering'].includes(k))continue;lines.push(`${f.label}: ${f.options[Number(input[k])][0]} [${r.parts[k]}]`);}lines.push(`RQD: ${input.rqd}% [${r.parts.rqd}]`,`Condition method: ${input.conditionMode==='overall'?'overall description':'five sub-parameters'}`);if(input.conditionMode==='overall')lines.push($('condition-overall').selectedOptions[0].textContent);lines.push('','SCORE BREAKDOWN',...breakdown(r).map(([k,v])=>`${k}: ${v}`),'','NOTES / EVIDENCE',input.notes||'No notes supplied.','','METHOD','Discrete RMR89 ratings; RQD exact thresholds enter the higher category. Negative raw totals are preserved; classification is floored at zero. Orientation is assessed by the user relative to excavation geometry. Slope adjustment is not SMR or a stability calculation.','Classification aid; not a support specification or design approval.','References: FHWA-NHI-09-010 Table 6-3; FHWA-NHI-16-072 Table 9-6.',`Exported: ${new Date().toISOString()}`);return lines;}
$('rmr-copy').onclick=async()=>{try{await navigator.clipboard.writeText(assessmentLines().join('\n'));status('Assessment copied, including observations and scores.');}catch(e){status('Clipboard unavailable. Use the PDF report or workspace download.');}};
$('rmr-pdf').onclick=()=>{try{const r=calculateRMR(state.rmr);if(!r.complete)throw Error('Complete required inputs.');if(!window.jspdf?.jsPDF)throw Error('PDF library has not loaded. Check your connection and try again.');exportRMR(new window.jspdf.jsPDF(),state.rmr,r,$('condition-overall').selectedOptions[0]?.textContent||'');status('RMR89 PDF downloaded with observations and scoring trace.');}catch(e){status('PDF export: '+e.message);}};
function showTab(tab){const plots=tab==='plots';$('plots-workspace').hidden=!plots;$('rmr-workspace').hidden=plots;for(const name of ['plots','rmr']){$('tab-'+name).classList.toggle('active',name===tab);$('tab-'+name).setAttribute('aria-pressed',String(name===tab));}}
$('tab-plots').onclick=()=>showTab('plots');$('tab-rmr').onclick=()=>showTab('rmr');
syncPlots();syncRMR();status(storageOK?'Ready. Changes save in this browser; download a workspace for backup.':'Browser storage unavailable or saved data could not be read. Download backups to retain work.');
