// exports.js — drone flight plan exporters: KML, Litchi CSV, plain waypoints CSV,
// GeoJSON, printable mission summary. Strict ES module. Depends on global JSZip
// loaded in HTML for KMZ (optional). Reuses attribution pattern from geopylanner.

export const ATTRIBUTION = 'Generated by G-FlightPlanner — free drone photogrammetry flight planner by Georesolve Africa — https://georesolveafrica.com/g-flightplanner.html';

function xmlEscape(value) {
  return String(value ?? '').replace(/[<>&"']/g, (c) => ({
    '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&apos;'
  }[c]));
}

function csvEscape(value) {
  const s = String(value ?? '');
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function downloadBlob(filename, blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
  try { window.showGFlightPlannerLeadAfterExport?.(); } catch (err) { /* non-critical */ }
}

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
}

// --- KML: flight path line + photo points (styled) ---
export function buildKML(result, meta = {}) {
  const folders = [];

  // Boundary
  if (result.boundary && result.boundary.latlngs && result.boundary.latlngs.length >= 3) {
    const ring = result.boundary.latlngs.map(([lat, lon]) => `${lon},${lat},${result.meta?.altitude || 0}`).join(' ');
    folders.push(`
    <Folder>
      <name>Boundary</name>
      <Placemark>
        <name>Flight boundary</name>
        <styleUrl>#boundaryStyle</styleUrl>
        <Polygon><tessellate>1</tessellate><outerBoundaryIs><LinearRing><coordinates>${ring}</coordinates></LinearRing></outerBoundaryIs></Polygon>
      </Placemark>
    </Folder>`);
  }

  // Flight path (single connected line + per-line segments).
  if (result.lines && result.lines.length) {
    const placemarks = result.lines.map((ln) => {
      const alt = result.meta?.altitude || 0;
      const coords = (ln.latlngs || []).map(([lat, lon]) => `${lon},${lat},${alt}`).join(' ');
      return `
      <Placemark>
        <name>${xmlEscape(ln.name || 'Flight line')}</name>
        <styleUrl>#flightLineStyle</styleUrl>
        <LineString><tessellate>1</tessellate><altitudeMode>relativeToGround</altitudeMode><coordinates>${coords}</coordinates></LineString>
      </Placemark>`;
    }).join('');
    folders.push(`
    <Folder>
      <name>Flight lines</name>${placemarks}
    </Folder>`);
  }

  // Photo points
  if (result.photoPoints && result.photoPoints.length) {
    const alt = result.meta?.altitude || 0;
    const placemarks = result.photoPoints.map((p) => {
      const lat = p.latlng ? p.latlng[0] : p.lat;
      const lon = p.latlng ? p.latlng[1] : p.lon;
      if (!Number.isFinite(lat) || !Number.isFinite(lon)) return '';
      return `
      <Placemark>
        <name>${xmlEscape(p.label || p.point_id || 'Photo')}</name>
        <description>${xmlEscape(`Trigger at ${p.label || ''} — altitude ${alt} m AGL`)}</description>
        <styleUrl>#photoPointStyle</styleUrl>
        <Point><altitudeMode>relativeToGround</altitudeMode><coordinates>${lon},${lat},${alt}</coordinates></Point>
      </Placemark>`;
    }).join('');
    folders.push(`
    <Folder>
      <name>Photo trigger points (${result.photoPoints.length})</name>${placemarks}
    </Folder>`);
  }

  const docName = xmlEscape(meta.name || 'G-FlightPlanner mission');
  const altComment = `Flight altitude AGL: ${result.meta?.altitude || '?'} m | GSD: ${result.stats?.gsd || '?'} cm/px | Photos: ${result.stats?.photoCount || 0}`;
  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${docName}</name>
    <description>${xmlEscape(ATTRIBUTION + ' — ' + altComment)}</description>
    <Style id="boundaryStyle">
      <LineStyle><color>ff345363</color><width>2</width></LineStyle>
      <PolyStyle><color>264da34d</color><fill>1</fill><outline>1</outline></PolyStyle>
    </Style>
    <Style id="flightLineStyle">
      <LineStyle><color>ff27ae60</color><width>3</width></LineStyle>
    </Style>
    <Style id="photoPointStyle">
      <IconStyle><color>ffe67e22</color><scale>0.5</scale><Icon><href>https://maps.google.com/mapfiles/kml/shapes/camera.png</href></Icon></IconStyle>
      <LabelStyle><scale>0.6</scale></LabelStyle>
    </Style>${folders.join('')}
  </Document>
</kml>`;
}

export function exportKML(result, meta = {}) {
  const kml = buildKML(result, meta);
  downloadBlob(`${meta.filename || 'flightplan'}_${timestamp()}.kml`, new Blob([kml], { type: 'application/vnd.google-earth.kml+xml' }));
}

export function exportKMZ(result, meta = {}) {
  if (!window.JSZip) { throw new Error('JSZip library not loaded — export KML instead.'); }
  const zip = new JSZip();
  const kml = buildKML(result, meta);
  zip.file('doc.kml', kml);
  zip.file('README.txt', `${meta.name || 'G-FlightPlanner mission'}\n\n${ATTRIBUTION}\nGenerated: ${new Date().toISOString()}\n`);
  return zip.generateAsync({ type: 'blob', compression: 'DEFLATE' }).then((blob) => {
    downloadBlob(`${meta.filename || 'flightplan'}_${timestamp()}.kmz`, blob);
  });
}

// --- Litchi mission CSV ---
// Header per Litchi mission hub import. Each waypoint = one row. Photo triggers
// are encoded as their own waypoints with actiontype1 = 1 (take photo). The
// navigation corner waypoints use actiontype1 = -1 (no action).
export function exportLitchiCSV(result, meta = {}) {
  const header = [
    'latitude', 'longitude', 'altitude(m)', 'heading', 'curvesize', 'rotationdir',
    'gimbalmode', 'gimbalpitchangle',
    'actiontype1', 'actionparam1', 'actiontype2', 'actionparam2',
    'actiontype3', 'actionparam3', 'actiontype4', 'actionparam4',
    'actiontype5', 'actionparam5', 'actiontype6', 'actionparam6',
    'actiontype7', 'actionparam7', 'actiontype8', 'actionparam8',
    'actiontype9', 'actionparam9', 'actiontype10', 'actionparam10',
    'speed'
  ];
  const rows = [header.join(',')];
  const alt = result.meta?.altitude || 50;
  const speed = result.meta?.flightSpeed || 8;
  // Litchi gimbal: 2 = needed angle, pitch -90 = nadir (straight down) for photogrammetry.
  const gimbalMode = 2;
  const gimbalPitch = -90;
  // actiontype: -1 = No Action, 0 = Stay For, 1 = Take Photo, 2 = Start Recording, 3 = Stop Recording
  const PHOTO_ACTION = 1;
  const NO_ACTION = -1;
  // curvesize 0 = fly straight to waypoint; rotationdir 0 = auto.
  const buildRow = (lat, lon, actionType, actionParam) => {
    const cells = [
      lat.toFixed(7), lon.toFixed(7), alt.toFixed(1), 0, 0, 0,
      gimbalMode, gimbalPitch,
      actionType, actionParam,
      -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0,
      speed
    ];
    return cells.map(csvEscape).join(',');
  };

  // Interleave: navigation waypoints + photo trigger waypoints in flight order.
  // result.waypoints holds the navigation vertices in serpentine order; result.photoPoints
  // holds photos. We walk them in chainage order per line via the waypoints list, and
  // insert photo points between consecutive waypoints by matching line_id.
  const navWps = result.waypoints || [];
  const photosByLine = {};
  for (const p of (result.photoPoints || [])) {
    const k = p.line_id || '';
    if (!photosByLine[k]) photosByLine[k] = [];
    photosByLine[k].push(p);
  }

  // Build a flat ordered list: for each nav waypoint, output it; between start and end
  // of the same line, output the photo points sorted by chainage in flight direction.
  // Because nav waypoints are paired (start, end) per line, we walk pairs.
  for (let i = 0; i + 1 < navWps.length; i += 2) {
    const startWp = navWps[i];
    const endWp = navWps[i + 1];
    if (!startWp || !endWp || startWp.line_id !== endWp.line_id) {
      // Fallback: just emit the waypoint alone.
      if (startWp) rows.push(buildRow(startWp.latlng[0], startWp.latlng[1], NO_ACTION, 0));
      continue;
    }
    // Start nav waypoint (no photo action).
    rows.push(buildRow(startWp.latlng[0], startWp.latlng[1], NO_ACTION, 0));
    // Photos for this line, sorted by chainage ascending (forward) — works for serpentine
    // because photoPoints were generated in the correct direction per line.
    const linePhotos = photosByLine[startWp.line_id] || [];
    for (const ph of linePhotos) {
      rows.push(buildRow(ph.latlng[0], ph.latlng[1], PHOTO_ACTION, 0));
    }
    // End nav waypoint.
    rows.push(buildRow(endWp.latlng[0], endWp.latlng[1], NO_ACTION, 0));
  }
  // Trailing unpaired waypoint if any.
  if (navWps.length % 2 === 1) {
    const last = navWps[navWps.length - 1];
    rows.push(buildRow(last.latlng[0], last.latlng[1], NO_ACTION, 0));
  }

  const csv = `# ${ATTRIBUTION}\n# Generated: ${new Date().toISOString()}\n# Altitude AGL: ${alt} m | Speed: ${speed} m/s | Gimbal pitch: ${gimbalPitch}° (nadir)\n${rows.join('\n')}\n`;
  downloadBlob(`${meta.filename || 'litchi_mission'}_${timestamp()}.csv`, new Blob([csv], { type: 'text/csv' }));
}

// --- Plain waypoints CSV (photo points only) ---
export function exportWaypointsCSV(result, meta = {}) {
  const header = `# ${ATTRIBUTION}\n# Generated: ${new Date().toISOString()}\n# Altitude AGL: ${result.meta?.altitude || '?'} m | GSD: ${result.stats?.gsd || '?'} cm/px\n`;
  const cols = ['line_id', 'point_id', 'chainage_m', 'easting', 'northing', 'utm_zone', 'latitude', 'longitude', 'altitude_m'];
  const lines = [header + cols.join(',')];
  for (const p of (result.photoPoints || [])) {
    const row = [
      p.line_id ?? '',
      p.point_id ?? p.label ?? '',
      p.chainage ?? '',
      p.easting ?? '',
      p.northing ?? '',
      p.utm_zone ?? '',
      p.latlng ? p.latlng[0] : (p.lat ?? ''),
      p.latlng ? p.latlng[1] : (p.lon ?? ''),
      result.meta?.altitude ?? ''
    ];
    lines.push(row.map(csvEscape).join(','));
  }
  const csv = lines.join('\n') + '\n';
  downloadBlob(`${meta.filename || 'waypoints'}_${timestamp()}.csv`, new Blob([csv], { type: 'text/csv' }));
}

// --- GeoJSON ---
export function exportGeoJSON(result, meta = {}) {
  const features = [];
  const alt = result.meta?.altitude || 0;
  if (result.boundary && result.boundary.latlngs) {
    const ring = result.boundary.latlngs.map(([lat, lon]) => [lon, lat]);
    if (ring.length >= 3 && ring[0][0] !== ring[ring.length - 1][0]) ring.push(ring[0]);
    features.push({ type: 'Feature', properties: { name: 'boundary' }, geometry: { type: 'Polygon', coordinates: [ring] } });
  }
  for (const ln of (result.lines || [])) {
    features.push({
      type: 'Feature',
      properties: { name: ln.name, kind: 'flight_line', altitude: alt },
      geometry: { type: 'LineString', coordinates: (ln.latlngs || []).map(([lat, lon]) => [lon, lat, alt]) }
    });
  }
  for (const p of (result.photoPoints || [])) {
    const lat = p.latlng ? p.latlng[0] : p.lat;
    const lon = p.latlng ? p.latlng[1] : p.lon;
    if (Number.isFinite(lat) && Number.isFinite(lon)) {
      features.push({
        type: 'Feature',
        properties: { name: p.label, line_id: p.line_id, chainage: p.chainage, kind: 'photo' },
        geometry: { type: 'Point', coordinates: [lon, lat, alt] }
      });
    }
  }
  const gj = {
    type: 'FeatureCollection',
    features,
    metadata: { generator: 'G-FlightPlanner', attribution: ATTRIBUTION, generated: new Date().toISOString() }
  };
  downloadBlob(`${meta.filename || 'flightplan'}_${timestamp()}.geojson`, new Blob([JSON.stringify(gj, null, 2)], { type: 'application/geo+json' }));
}

// --- Printable mission summary sheet (HTML string for the print container) ---
export function buildPrintSummary(result, meta = {}) {
  const s = result.stats || {};
  const m = result.meta || {};
  const cam = m.camera || {};
  const paramRows = [
    ['Camera', cam.label || '—'],
    ['Sensor', cam.sensorWidth ? `${cam.sensorWidth} × ${cam.sensorHeight} mm` : '—'],
    ['Image', cam.imageWidth ? `${cam.imageWidth} × ${cam.imageHeight} px` : '—'],
    ['Focal length', cam.focalLength ? `${cam.focalLength} mm` : '—'],
    ['Target GSD', `${s.gsd ?? '?'} cm/px`],
    ['Flight altitude AGL', `${s.altitude ?? '?'} m`],
    ['Front overlap', `${s.frontOverlapPct ?? '?'} %`],
    ['Side overlap', `${s.sideOverlapPct ?? '?'} %`],
    ['Flight direction', `${s.lineAzimuth ?? '?'}°`],
    ['Flight speed', `${m.flightSpeed ?? '?'} m/s`],
    ['Crosshatch', s.crosshatch ? 'Yes (double grid)' : 'No'],
    ['Boundary buffer', `${m.buffer ?? 0} m`],
    ['Usable flight per battery', `${m.usableFlightMin ?? 20} min`]
  ];
  const statRows = [
    ['Area', `${s.areaHa ?? '?'} ha`],
    ['Flight lines', s.lineCount ?? '?'],
    ['Photo count', s.photoCount ?? '?'],
    ['Navigation waypoints', s.waypointCount ?? '?'],
    ['Line spacing', `${s.lineSpacing ?? '?'} m`],
    ['Photo interval', `${s.photoInterval ?? '?'} m (${s.photoIntervalSeconds ?? '?'} s)`],
    ['Footprint', `${s.footprintWidth ?? '?'} × ${s.footprintHeight ?? '?'} m`],
    ['Total flight distance', `${s.flightDistanceKm ?? '?'} km`],
    ['Est. flight time (incl. turns)', `${s.flightTimeMin ?? '?'} min`],
    ['Batteries required', s.batteries ?? '?']
  ];
  const warn = (result.warnings || []).map((w) => `<li>${w.text}</li>`).join('');
  const paramMap = paramRows.map(([k, v]) => `<tr><th>${k}</th><td>${v}</td></tr>`).join('');
  const statMap = statRows.map(([k, v]) => `<tr><th>${k}</th><td>${v}</td></tr>`).join('');
  return `
    <h2>G-FlightPlanner — Drone photogrammetry mission</h2>
    <p class="gp-print-attrib">${ATTRIBUTION}</p>
    <p class="gp-print-attrib"><strong>Disclaimer:</strong> Planning-grade output. Import into Litchi / DJI Pilot 2 / UgCS to fly. Always verify local UAV regulations and obtain permits (Uganda CAA, Rwanda RCAA, etc.).</p>
    <table class="gp-print-tbl"><caption>Parameters</caption>${paramMap}</table>
    <table class="gp-print-tbl"><caption>Mission statistics</caption>${statMap}</table>
    ${warn ? `<h3 style="color:#c0392b; margin-top:14px;">Warnings</h3><ul class="fp-warn-list">${warn}</ul>` : ''}
    <p class="gp-print-foot">Generated ${new Date().toLocaleString()}</p>`;
}

export function downloadText(filename, text, type = 'text/plain') {
  downloadBlob(filename, new Blob([text], { type }));
}
