'use strict';
/*
 * wire-webp.cjs
 * Rewires the Georesolve site source to use the pre-generated .webp images
 * that already live next to every .jpeg/.jpg/.png in resources/.
 *
 * What it does (source files only — dist/ is regenerated by build.js):
 *   1. Converts <img src>, url(), and data-string image references from
 *      .jpeg/.jpg/.png to .webp WHERE a matching .webp sibling exists.
 *   2. Forces the hero background to the dedicated hero-geoscience-1200.webp.
 *   3. Adds width/height (read from the .webp) and decoding="async" to every
 *      static <img> (build.js adds the same to dynamically rendered imgs).
 *   4. Adds <link rel="preload" as="image"> for the hero in index.html <head>.
 *
 * Explicitly leaves alone: og:image / twitter:image (absolute JPEG — social
 * scrapers prefer JPEG), favicon links, and JSON-LD image fields.
 *
 * It NEVER re-encodes or re-compresses any image; it only reads dimensions.
 */

const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const ROOT = path.resolve(__dirname, '..');

// ---------------------------------------------------------------------------
// 1. Discover every .webp under resources/ and preload its pixel dimensions.
// ---------------------------------------------------------------------------
const webpSet = new Set();      // relative posix paths of all .webp files
const dimsCache = new Map();    // relative posix webp path -> {width,height}

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full);
    } else if (entry.name.toLowerCase().endsWith('.webp')) {
      webpSet.add(path.relative(ROOT, full).replace(/\\/g, '/'));
    }
  }
}
walk(path.join(ROOT, 'resources'));

async function preloadDims() {
  for (const rel of webpSet) {
    try {
      const meta = await sharp(path.join(ROOT, rel)).metadata();
      dimsCache.set(rel, { width: meta.width, height: meta.height });
    } catch (e) {
      dimsCache.set(rel, null);
    }
  }
}

// ---------------------------------------------------------------------------
// 2. Path helpers
// ---------------------------------------------------------------------------
function stripUp(src) {
  let s = src;
  while (s.startsWith('../')) s = s.slice(3);
  return s.replace(/\\/g, '/');
}

// Convert a single image reference to its .webp sibling (hero -> 1200 variant).
function toWebp(src) {
  if (!src) return src;
  const hero = src.match(/^(.*\/)?(hero-geoscience)(?:\.jpeg|\.jpg|\.png|\.webp)?$/i);
  if (hero) {
    const dir = hero[1] || '';
    return dir + 'hero-geoscience-1200.webp';
  }
  if (!/\.(jpeg|jpg|png)$/i.test(src)) return src;
  const webpRel = src.replace(/\.(jpeg|jpg|png)$/i, '.webp');
  return webpSet.has(stripUp(webpRel)) ? webpRel : src;
}

function dimsFor(src) {
  const d = dimsCache.get(stripUp(src));
  return d || null;
}

// ---------------------------------------------------------------------------
// 3. Converters
// ---------------------------------------------------------------------------
function convertImgTag(tag) {
  // Convert the src extension to .webp where available.
  tag = tag.replace(/(src\s*=\s*)(["'])(.*?)\2/gi,
    (m, pre, q, val) => pre + q + toWebp(val) + q);

  const sm = tag.match(/src\s*=\s*["']([^"']*)["']/i);
  if (sm) {
    const d = dimsFor(toWebp(sm[1]));
    if (d) {
      if (!/\bwidth\s*=/.test(tag)) {
        tag = tag.replace(/<img\b/i, `<img width="${d.width}" height="${d.height}"`);
      }
      if (!/\bdecoding\s*=/.test(tag)) {
        tag = tag.replace(/<img\b/i, `<img decoding="async"`);
      }
    }
  }
  return tag;
}

function convertHtml(html) {
  // Inline / CSS url(...) references (covers <style> and style="" backgrounds).
  html = html.replace(/url\(\s*(['"]?)([^)'"]*?)\1\s*\)/gi,
    (mm, q, p) => {
      const conv = toWebp(p);
      return conv === p ? mm : `url(${q}${conv}${q})`;
    });
  // <img> tags.
  html = html.replace(/<img\b[^>]*>/gi, convertImgTag);
  return html;
}

function convertCss(css) {
  return css.replace(/url\(\s*(['"]?)([^)'"]*?)\1\s*\)/gi,
    (mm, q, p) => {
      const conv = toWebp(p);
      return conv === p ? mm : `url(${q}${conv}${q})`;
    });
}

// JSON / JS data files: quoted resource image strings -> .webp.
function convertData(text) {
  return text.replace(/(["'])((?:\.\.\/)?resources\/[^"']*?)\.(jpeg|jpg|png)\1/gi,
    (mm, q, p, ext) => q + toWebp(p + '.' + ext) + q);
}

// ---------------------------------------------------------------------------
// 4. File list (source only)
// ---------------------------------------------------------------------------
const rootHtml = fs.readdirSync(ROOT)
  .filter(f => f.endsWith('.html') && fs.statSync(path.join(ROOT, f)).isFile());

const targets = [
  ...rootHtml.map(f => path.join(ROOT, f)),
  path.join(ROOT, 'partials', 'header.html'),
  path.join(ROOT, 'partials', 'footer.html'),
  path.join(ROOT, 'quick-footer-inject.html'),
  path.join(ROOT, 'footer-component.js'),
  path.join(ROOT, 'js', 'header-component.js'),
  path.join(ROOT, 'projects.json'),
  path.join(ROOT, 'projects-data.js'),
];

const cssTargets = fs.readdirSync(path.join(ROOT, 'css'))
  .filter(f => f.endsWith('.css'))
  .map(f => path.join(ROOT, 'css', f));

// ---------------------------------------------------------------------------
// 5. Run
// ---------------------------------------------------------------------------
async function run() {
  await preloadDims();

  let changed = 0;

  for (const file of targets) {
    if (!fs.existsSync(file)) continue;
    const before = fs.readFileSync(file, 'utf8');
    let after;
    if (file.endsWith('.css')) {
      after = convertCss(before);
    } else if (file.endsWith('.json') || file.endsWith('.js')) {
      after = convertData(before);
    } else {
      after = convertHtml(before);
    }
    if (after !== before) {
      fs.writeFileSync(file, after, 'utf8');
      changed++;
      console.log(`[wire-webp] updated ${path.relative(ROOT, file)}`);
    }
  }

  for (const file of cssTargets) {
    const before = fs.readFileSync(file, 'utf8');
    const after = convertCss(before);
    if (after !== before) {
      fs.writeFileSync(file, after, 'utf8');
      changed++;
      console.log(`[wire-webp] updated ${path.relative(ROOT, file)}`);
    }
  }

  // Preload the hero image in index.html <head>.
  const indexFile = path.join(ROOT, 'index.html');
  if (fs.existsSync(indexFile)) {
    let html = fs.readFileSync(indexFile, 'utf8');
    const preloadHref = 'resources/hero-geoscience-1200.webp';
    const preloadTag = `<link rel="preload" as="image" href="${preloadHref}">`;
    if (!html.includes(preloadHref)) {
      // Insert right after the twitter:image meta so it is early in <head>.
      const marker = /(<meta name="twitter:image"[^>]*>)/i;
      if (marker.test(html)) {
        html = html.replace(marker, `$1\n    ${preloadTag}`);
      } else {
        html = html.replace('</head>', `    ${preloadTag}\n</head>`);
      }
      fs.writeFileSync(indexFile, html, 'utf8');
      changed++;
      console.log('[wire-webp] added hero preload to index.html');
    }
  }

  console.log(`[wire-webp] done. ${changed} file(s) changed. ${webpSet.size} webp images indexed.`);
}

run().catch(e => { console.error(e); process.exit(1); });
